# Generated by Django 6.0.3 on 2026-04-02 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Location"
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_sample_id",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Original sample ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "count",
                    models.PositiveSmallIntegerField(verbose_name="Number of throws"),
                ),
                (
                    "length",
                    models.PositiveSmallIntegerField(verbose_name="Throw length"),
                ),
                (
                    "samples_sum",
                    models.PositiveSmallIntegerField(verbose_name="Number of samples"),
                ),
                ("process_date", models.DateField(verbose_name="Sample handover date")),
                ("complete_date", models.DateField(verbose_name="Data delivery date")),
                (
                    "complete",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "store",
                    models.BooleanField(default=True, verbose_name="Keep stored"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="samples.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="samples.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample",
                "verbose_name_plural": "Samples",
            },
        ),
    ]
