# Generated by Django 6.0.7 on 2026-07-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="lost",
            field=models.BooleanField(default=False, verbose_name="Lost sample"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="count",
            field=models.PositiveSmallIntegerField(
                help_text="Number of throws in the sample. If that was not possible, enter 0 - Details are in the laboratory’s main database.",
                verbose_name="Number of throws",
            ),
        ),
    ]
