# Generated by Django 6.0.7 on 2026-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0003_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="sample_processor",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="zooplankton_analyst",
            field=models.BooleanField(
                default=False, verbose_name="zooplankton analyst"
            ),
        ),
    ]
