# Generated by Django 6.0.7 on 2026-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0004_remove_userprofile_sample_processor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="zooplankton_analyst",
            field=models.BooleanField(
                default=False, verbose_name="Zooplankton analyst"
            ),
        ),
    ]
