# Generated by Django 6.0.7 on 2026-07-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0005_alter_userprofile_zooplankton_analyst"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="zooplankton_analyst",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"zooplankton_analyst": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="samples.userprofile",
                verbose_name="Zooplankton analyst",
            ),
        ),
    ]
