# Generated by Django 6.0.7 on 2026-07-14 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0006_sample_zooplankton_analyst"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Record created",
            ),
            preserve_default=False,
        ),
    ]
