# Generated by Django 6.0.7 on 2026-07-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0007_sample_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="process_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Sample handover date"
            ),
        ),
    ]
