# Generated by Django 6.0.7 on 2026-07-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0008_alter_sample_process_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Project deadline"
            ),
        ),
    ]
