# Generated by Django 6.0.7 on 2026-07-15 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0009_project_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sample",
                to="samples.project",
                verbose_name="Project",
            ),
        ),
    ]
