# Generated by Django 6.0.7 on 2026-07-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0010_alter_sample_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_done",
            field=models.BooleanField(default=False, verbose_name="Project done"),
        ),
    ]
